language: cpp
sudo: required


before_install:
  - sudo echo deb http://cz.archive.ubuntu.com/ubuntu xenial main universe >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -y -qq install cmake3 extra-cmake-modules libglib2.0-0 qt5-default

install:
  - sh ./build.sh